### ISSUE TITLE
Data request UI

### ISSUE THREAD

**Issue by aidiss** [atviriduomenys/manifest#7]
The way to propose a data need is documented in the readme.
However, I suggest we could really use more "human friendly" way of expressing interest in a dataset.

I think https://www.data.gov/data-request/ is a good example.

A form could contain:

- Dataset Name (string) (Required)
- Dataset Description (string) (Required)
- Related Agency (list) (Optional)
- How would you like the data provided? (choose from api or a file) (Optional) 

And optional personal information.

Then some script could create pull request on behalf of the person.
I guess we would need some kind of OpenDataBot, a non-human user that would create pull requests on behalf of human beings :)

**Comment by sirex** [comment]
Currently the plan is to use Github issues for such UI. In order to make things more structured, Github issue templates can be used.

Since there is almost no value of a high level data requests written in plain text, someone should take that data request and turn it into yaml file, with list of data fields, using common vocabulary for object and field names, using a common data model between all data sources, with references to other sources, transformations and projects. Only having those detailed yaml files, we can fully employ scripts, that could reliably calculate if needed data are available and if not, how it is difficult to get the data.

I tried free form data requests already, and learned, that it is mostly useless.

**Comment by sirex** [comment]
Closing this, because GitHub is a data request UI.
